### ISSUE TITLE
Functionality Breaks When Security Context Is Included In Pod Spec

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [fstab/cifs#16]
This plugin has been working great for months up until today where I tried to include a securityContext in the Pod spec that uses a pvc that is bound to a pv that is configured to use this plugin.
Example of what doesn't work (free written to give the gist of it)
```
apiVersion: v1
kind: Pod
metadata:
  name: example-doesnt-work
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: doesntwork
      image: nginx
      volumeMounts:
      - mountPath: "/test-mount"
         name: mounttotest
  volumes:
    - name: mounttotest
      persistentVolumeClaim:
        claimName: cifs-vol-created-using-flexvol-plugin-pvc  
``` 
When I don't include the securityContext, everything works great per usual.  The behavior I see is the pod gets stuck in a ContainerCreating state until the volume mounts timeout.  There are no meaningful logs in kubelet, docker, or the Cluster logs.  Does anyone have advice on what is happening or how to see what is happening?
